apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: realyx
data:
  NODE_ENV: "production"
  PORT: "3001"
  WS_PORT: "3002"
  METRICS_PORT: "9090"
  CHAIN_ID: "71"
  RPC_URL: "https://evmtestnet.confluxrpc.com"
  RPC_FALLBACK_URL: "https://evmtestnet.confluxrpc.org"
  TRADING_CORE_ADDRESS: "0x64f277f73bfc81Ad80286a4266c0E0613d867Df3"
  VAULT_CORE_ADDRESS: "0xB5C983d038caA21f4a9520b0EFAb2aD71DE4e714"
  ORACLE_AGGREGATOR_ADDRESS: "0x89cC8eAbF2e967d81FD04D1023298A3bDcE67450"
  SUBGRAPH_URL: "https://api.thegraph.com/subgraphs/name/<your-org>/realyx"
